easy_admin:
    entities:
        # List the entity class name you want to manage
        User:
            class: App\Entity\User
            label: 'Users list'
        Category:
            class: App\Entity\Category
            label: 'Categories'
        Product:
            class: App\Entity\Product
            label: 'Products list'
            icon: 'shopping-basket'
        Attribute:
            class: App\Entity\Attribute
            label: 'Attributes'
        Review:
            class: App\Entity\Review
            label: 'Reviews'
        Orders:
            class: App\Entity\Orders
        ContactUs:
            class: App\Entity\ContactUs
            label: 'Feedback'
    site_name: '<img src="../img/logo.png" /><br />PetSymfo <em style="font-size: 80%;">Megacorp.</em>'
    user:
        display_name: true
        display_avatar: true
        name_property_path: 'email'
        avatar_property_path: 'avatarUrl'
    design:
        brand_color: '#D10024'
        assets:
            favicon: 'bundles/easyadmin/images/favicon.ico'
            css:
                - 'css/admin.css'
        menu:
            - { entity: 'User', , icon: 'users', children: ['User', 'Orders'], label: 'Users' }
            - { entity: 'Product', icon: 'shopping-basket', children: ['Product', 'Category', 'Attribute', 'Review'], label: 'Products' }
            - { entity: 'ContactUs', icon: 'envelope', label: 'Feedback' }
